// <auto-generated />
namespace bcast.data.sqlserver.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class resetcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resetcode));
        
        string IMigrationMetadata.Id
        {
            get { return "201504190045357_resetcode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
